SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK AS B
join author as A on B.AUTHOR_ID = A.AUTHOR_ID
join (
    SELECT BOOK_ID, SUM(SALES) AS SALES 
    FROM BOOK_SALES 
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
    ) AS S ON B.book_id = S.book_id
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY desc  
    