SELECT
    P.PRODUCT_CODE,
    SUM(O.SALES_AMOUNT) * P.PRICE AS SALES
FROM
    PRODUCT AS P
JOIN
    OFFLINE_SALE AS O
    ON
        P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID
ORDER BY
    SALES DESC,
    PRODUCT_CODE ASC

