SELECT
    M.MEMBER_ID,
    M.MEMBER_NAME,
    M.GENDER,
    DATE_FORMAT(M.DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM
    MEMBER_PROFILE AS M
WHERE 
    M.GENDER = 'W'
    AND
    M.DATE_OF_BIRTH LIKE '____-03-%'
    AND
    M.TLNO IS NOT NULL