SELECT
    B.CATEGORY AS CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM
    BOOK AS B
JOIN
    BOOK_SALES AS S
ON
    B.BOOK_ID = S.BOOK_ID
WHERE
    S.SALES_DATE LIKE '2022-01%'
GROUP BY
    CATEGORY
ORDER BY
    B.CATEGORY ASC